# Form implementation generated from reading ui file 'ui_main.ui'
#
# Created by: PyQt6 UI code generator 6.0.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(940, 560)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(940, 560))
        self.styleSheet = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.styleSheet.sizePolicy().hasHeightForWidth())
        self.styleSheet.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("SimHei")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        self.styleSheet.setFont(font)
        self.styleSheet.setStyleSheet("/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"\n"
"SET APP STYLESHEET - FULL STYLES HERE\n"
"DARK THEME - DRACULA COLOR BASED\n"
"\n"
"# BY: WANDERSON M.PIMENTA\n"
"# PROJECT MADE WITH: Qt Designer and PySide6\n"
"# V: 1.0.0\n"
"#\n"
"# This project can be used freely for all uses, as long as they maintain the\n"
"# respective credits only in the Python scripts, any information in the visual\n"
"# interface (GUI) can be modified without any implication.\n"
"#\n"
"# There are limitations on Qt licenses if you want to use your products\n"
"# commercially, I recommend reading them on the official website:\n"
"# https://doc.qt.io/qtforpython/licenses.html\n"
"\n"
"///////////////////////////////////////////////////////////////////////////////////////////////// */\n"
"\n"
"QWidget{\n"
"    color: #333;\n"
"    font: 10pt \"SimHei\";\n"
"}\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"Tooltip */\n"
"QToolTip {\n"
"    color: #333;\n"
"    background-color: #f8f8f2;\n"
"    border: 1px solid #CCC;\n"
"    background-image: none;\n"
"    background-position: left center;\n"
"    background-repeat: no-repeat;\n"
"    border: none;\n"
"    border-left: 2px solid rgb(255, 121, 198);\n"
"    text-align: left;\n"
"    padding-left: 8px;\n"
"    margin: 0px;\n"
"}\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"classApp */\n"
"#classApp {\n"
"    background-color: #f8f8f2;\n"
"    border: 1px solid #CCC;\n"
"    color: #44475a;\n"
"}\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"Left Menu */\n"
"#leftMenuBg {\n"
"    background-color: #6272a4;\n"
"}\n"
"#topLogo {\n"
"    background-color: #6272a4;\n"
"    background-image: url(:/images/images/images/PyDracula.png);\n"
"    background-position: centered;\n"
"    background-repeat: no-repeat;\n"
"}\n"
"#titleLeftApp { font: 63 12pt \"SimHei Semibold\"; color: #f8f8f2; }\n"
"#titleLeftDescription { font: 8pt \"SimHei\"; color: #bd93f9; }\n"
"\n"
"/* MENUS */\n"
"#topMenu .QPushButton {\n"
"    background-position: left center;\n"
"    background-repeat: no-repeat;\n"
"    border: none;\n"
"    border-left: 22px solid transparent;\n"
"    background-color: transparent;\n"
"    text-align: left;\n"
"    padding-left: 44px;\n"
"    color: #f8f8f2;\n"
"}\n"
"#topMenu .QPushButton:hover {\n"
"    background-color: #bd93f9;\n"
"}\n"
"#topMenu .QPushButton:pressed {\n"
"    background-color: #ff79c6;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"#bottomMenu .QPushButton {\n"
"    background-position: left center;\n"
"    background-repeat: no-repeat;\n"
"    border: none;\n"
"    border-left: 20px solid transparent;\n"
"    background-color:transparent;\n"
"    text-align: left;\n"
"    padding-left: 44px;\n"
"    color: #f8f8f2;\n"
"}\n"
"#bottomMenu .QPushButton:hover {\n"
"    background-color: #bd93f9;\n"
"}\n"
"#bottomMenu .QPushButton:pressed {\n"
"    background-color: #ff79c6;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"#leftMenuFrame{\n"
"    border-top: 3px solid #6a7cb1;\n"
"}\n"
"\n"
"/* Toggle Button */\n"
"#toggleButton {\n"
"    background-position: left center;\n"
"    background-repeat: no-repeat;\n"
"    border: none;\n"
"    border-left: 20px solid transparent;\n"
"    background-color: #5b6996;\n"
"    text-align: left;\n"
"    padding-left: 44px;\n"
"    color: #f8f8f2;\n"
"}\n"
"#toggleButton:hover {\n"
"    background-color: #bd93f9;\n"
"}\n"
"#toggleButton:pressed {\n"
"    background-color: #ff79c6;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"/* Title Menu */\n"
"#titleRightInfo { padding-left: 10px; }\n"
"\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"Extra Tab */\n"
"#extraLeftBox {\n"
"    background-color: #495474;\n"
"    color: #f8f8f2;\n"
"}\n"
"#extraTopBg{\n"
"    background-color: rgb(189, 147, 249)\n"
"}\n"
"\n"
"/* Icon */\n"
"#extraIcon {\n"
"    background-position: center;\n"
"    background-repeat: no-repeat;\n"
"    background-image: url(:/icons/images/icons/icon_settings.png);\n"
"}\n"
"\n"
"/* Label */\n"
"#extraLabel { color: rgb(255, 255, 255); }\n"
"\n"
"/* Btn Close */\n"
"#extraCloseColumnBtn { background-color: rgba(255, 255, 255, 0); border: none;  border-radius: 5px; }\n"
"#extraCloseColumnBtn:hover { background-color: rgb(196, 161, 249); border-style: solid; border-radius: 4px; }\n"
"#extraCloseColumnBtn:pressed { background-color: rgb(180, 141, 238); border-style: solid; border-radius: 4px; }\n"
"\n"
"/* Extra Content */\n"
"#extraContent{\n"
"    border-top: 3px solid #6272a4;\n"
"}\n"
"\n"
"/* Extra Top Menus */\n"
"#extraTopMenu .QPushButton {\n"
"    background-position: left center;\n"
"    background-repeat: no-repeat;\n"
"    border: none;\n"
"    border-left: 22px solid transparent;\n"
"    background-color:transparent;\n"
"    text-align: left;\n"
"    padding-left: 44px;\n"
"    color: #f8f8f2;\n"
"}\n"
"#extraTopMenu .QPushButton:hover {\n"
"    background-color: #5d6c99;\n"
"}\n"
"#extraTopMenu .QPushButton:pressed {\n"
"    background-color: rgb(189, 147, 249);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"Content App */\n"
"#contentTopBg{\n"
"    background-color: #6272a4;\n"
"}\n"
"#contentBottom{\n"
"    border-top: 3px solid #bd93f9;\n"
"}\n"
"#titleRightInfo{\n"
"    color: #f8f8f2;\n"
"}\n"
"\n"
"/* Top Buttons */\n"
"#rightButtons .QPushButton { background-color: rgba(255, 255, 255, 0); border: none;  border-radius: 5px; }\n"
"#rightButtons .QPushButton:hover { background-color: #bd93f9; border-style: solid; border-radius: 4px; }\n"
"#rightButtons .QPushButton:pressed { background-color: #ff79c6; border-style: solid; border-radius: 4px; }\n"
"\n"
"/* Theme Settings */\n"
"#extraRightBox { background-color: #495474; }\n"
"#themeSettingsTopDetail { background-color: #6272a4; }\n"
"\n"
"/* Bottom Bar */\n"
"#bottomBar { background-color: #495474 }\n"
"#bottomBar QLabel { font-size: 11px; color: #f8f8f2; padding-left: 10px; padding-right: 10px; padding-bottom: 2px; }\n"
"\n"
"/* CONTENT SETTINGS */\n"
"/* MENUS */\n"
"#contentSettings .QPushButton {\n"
"    background-position: left center;\n"
"    background-repeat: no-repeat;\n"
"    border: none;\n"
"    border-left: 22px solid transparent;\n"
"    background-color:transparent;\n"
"    text-align: left;\n"
"    padding-left: 44px;\n"
"    color: #f8f8f2;\n"
"}\n"
"#contentSettings .QPushButton:hover {\n"
"    background-color: #5d6c99;\n"
"}\n"
"#contentSettings .QPushButton:pressed {\n"
"    background-color: rgb(189, 147, 249);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"QTableWidget */\n"
"QTableWidget {\n"
"    background-color: transparent;\n"
"    padding: 10px;\n"
"    border-radius: 5px;\n"
"    gridline-color: #9faeda;\n"
"    outline: none;\n"
"    color:rgb(113, 126, 149);\n"
"}\n"
"QTableWidget::item{\n"
"    border-color: #9faeda;\n"
"    padding-left: 5px;\n"
"    padding-right: 5px;\n"
"    gridline-color: #9faeda;\n"
"}\n"
"QTableWidget::item:selected{\n"
"    background-color: rgb(189, 147, 249);\n"
"    color: #f8f8f2;\n"
"}\n"
"QHeaderView::section{\n"
"    background-color: #6272a4;\n"
"    max-width: 30px;\n"
"    border: none;\n"
"    border-style: none;\n"
"}\n"
"QTableWidget::horizontalHeader {\n"
"    background-color: #6272a4;\n"
"}\n"
"QHeaderView::section:horizontal\n"
"{\n"
"    border: 1px solid #6272a4;\n"
"    background-color: #6272a4;\n"
"    padding: 3px;\n"
"    border-top-left-radius: 7px;\n"
"    border-top-right-radius: 7px;\n"
"    color: #f8f8f2;\n"
"}\n"
"QHeaderView::section:vertical\n"
"{\n"
"    border: 1px solid #6272a4;\n"
"}\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"LineEdit */\n"
"QLineEdit {\n"
"    background-color: #6272a4;\n"
"    border-radius: 5px;\n"
"    border: 2px solid #6272a4;\n"
"    padding-left: 10px;\n"
"    selection-color: rgb(255, 255, 255);\n"
"    selection-background-color: rgb(255, 121, 198);\n"
"    color:  rgb(113, 126, 149);\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(64, 71, 88);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid #ff79c6;\n"
"}\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"QTextEdit */\n"
"QTextEdit {\n"
"    background-color: #6272a4;\n"
"    border-radius: 5px;\n"
"    border: 2px solid #6272a4;\n"
"    padding-left: 10px;\n"
"    selection-color: rgb(255, 255, 255);\n"
"    selection-background-color: rgb(255, 121, 198);\n"
"    color: rgb(113, 126, 149);\n"
"}\n"
"QTextEdit:hover {\n"
"    border: 2px solid rgb(64, 71, 88);\n"
"}\n"
"QTextEdit:focus {\n"
"    border: 2px solid #ff79c6;\n"
"}\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"PlainTextEdit */\n"
"QPlainTextEdit {\n"
"    background-color: #6272a4;\n"
"    border-radius: 5px;\n"
"    padding: 10px;\n"
"    selection-color: rgb(255, 255, 255);\n"
"    selection-background-color: rgb(255, 121, 198);\n"
"    color: #f8f8f2;\n"
"}\n"
"QPlainTextEdit  QScrollBar:vertical {\n"
"    width: 8px;\n"
" }\n"
"QPlainTextEdit  QScrollBar:horizontal {\n"
"    height: 8px;\n"
" }\n"
"QPlainTextEdit:hover {\n"
"    border: 2px solid rgb(64, 71, 88);\n"
"}\n"
"QPlainTextEdit:focus {\n"
"    border: 2px solid #ff79c6;\n"
"}\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"ScrollBars */\n"
"QScrollBar:horizontal {\n"
"    border: none;\n"
"    background: #6272a4;\n"
"    height: 8px;\n"
"    margin: 0px 21px 0 21px;\n"
"    border-radius: 0px;\n"
"}\n"
"QScrollBar::handle:horizontal {\n"
"    background: rgb(189, 147, 249);\n"
"    min-width: 25px;\n"
"    border-radius: 4px\n"
"}\n"
"QScrollBar::add-line:horizontal {\n"
"    border: none;\n"
"    background: #6272a4;\n"
"    width: 20px;\n"
"    border-top-right-radius: 4px;\n"
"    border-bottom-right-radius: 4px;\n"
"    subcontrol-position: right;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:horizontal {\n"
"    border: none;\n"
"    background: #6272a4;\n"
"    width: 20px;\n"
"    border-top-left-radius: 4px;\n"
"    border-bottom-left-radius: 4px;\n"
"    subcontrol-position: left;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::up-arrow:horizontal, QScrollBar::down-arrow:horizontal\n"
"{\n"
"     background: none;\n"
"}\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal\n"
"{\n"
"     background: none;\n"
"}\n"
" QScrollBar:vertical {\n"
"    border: none;\n"
"    background-color: #6272a4;\n"
"    width: 8px;\n"
"    margin: 21px 0 21px 0;\n"
"    border-radius: 0px;\n"
" }\n"
" QScrollBar::handle:vertical {\n"
"    background: rgb(189, 147, 249);\n"
"    min-height: 25px;\n"
"    border-radius: 4px\n"
" }\n"
" QScrollBar::add-line:vertical {\n"
"     border: none;\n"
"    background: #6272a4;\n"
"     height: 20px;\n"
"    border-bottom-left-radius: 4px;\n"
"    border-bottom-right-radius: 4px;\n"
"     subcontrol-position: bottom;\n"
"     subcontrol-origin: margin;\n"
" }\n"
" QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background: #6272a4;\n"
"     height: 20px;\n"
"    border-top-left-radius: 4px;\n"
"    border-top-right-radius: 4px;\n"
"     subcontrol-position: top;\n"
"     subcontrol-origin: margin;\n"
" }\n"
" QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"     background: none;\n"
" }\n"
"\n"
" QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"     background: none;\n"
" }\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"CheckBox */\n"
"QCheckBox::indicator {\n"
"    border: 3px solid #6272a4;\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    border-radius: 10px;\n"
"    background: #6272a4;\n"
"}\n"
"QCheckBox::indicator:hover {\n"
"    border: 3px solid rgb(119, 136, 187);\n"
"}\n"
"QCheckBox::indicator:checked {\n"
"    background: 3px solid #bd93f9;\n"
"    border: 3px solid #bd93f9;\n"
"    background-image: url(:/icons/images/icons/cil-check-alt.png);\n"
"}\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"RadioButton */\n"
"QRadioButton::indicator {\n"
"    border: 3px solid #6272a4;\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    border-radius: 10px;\n"
"    background: #6272a4;\n"
"}\n"
"QRadioButton::indicator:hover {\n"
"    border: 3px solid rgb(119, 136, 187);\n"
"}\n"
"QRadioButton::indicator:checked {\n"
"    background: 3px solid #bd93f9;\n"
"    border: 3px solid #bd93f9;\n"
"}\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"ComboBox */\n"
"QComboBox{\n"
"    background-color: #6272a4;\n"
"    border-radius: 5px;\n"
"    border: 2px solid #6272a4;\n"
"    padding: 5px;\n"
"    padding-left: 10px;\n"
"    color: #f8f8f2;\n"
"}\n"
"QComboBox:hover{\n"
"    border: 2px solid #7284b9;\n"
"}\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 25px;\n"
"    border-left-width: 3px;\n"
"    border-left-color: #6272a4;\n"
"    border-left-style: solid;\n"
"    border-top-right-radius: 3px;\n"
"    border-bottom-right-radius: 3px;\n"
"    background-image: url(:/icons/images/icons/cil-arrow-bottom.png);\n"
"    background-position: center;\n"
"    background-repeat: no-reperat;\n"
" }\n"
"QComboBox QAbstractItemView {\n"
"    color: #f8f8f2;\n"
"    background-color: #6272a4;\n"
"    padding: 10px;\n"
"    selection-background-color: #6272a4;\n"
"}\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"Sliders */\n"
"QSlider::groove:horizontal {\n"
"    border-radius: 5px;\n"
"    height: 10px;\n"
"    margin: 0px;\n"
"    background-color: #6272a4;\n"
"}\n"
"QSlider::groove:horizontal:hover {\n"
"    background-color: #6272a4;\n"
"}\n"
"QSlider::handle:horizontal {\n"
"    background-color: rgb(189, 147, 249);\n"
"    border: none;\n"
"    height: 10px;\n"
"    width: 10px;\n"
"    margin: 0px;\n"
"    border-radius: 5px;\n"
"}\n"
"QSlider::handle:horizontal:hover {\n"
"    background-color: rgb(195, 155, 255);\n"
"}\n"
"QSlider::handle:horizontal:pressed {\n"
"    background-color: rgb(255, 121, 198);\n"
"}\n"
"\n"
"QSlider::groove:vertical {\n"
"    border-radius: 5px;\n"
"    width: 10px;\n"
"    margin: 0px;\n"
"    background-color: #6272a4;\n"
"}\n"
"QSlider::groove:vertical:hover {\n"
"    background-color: #6272a4;\n"
"}\n"
"QSlider::handle:vertical {\n"
"    background-color: rgb(189, 147, 249);\n"
"    border: none;\n"
"    height: 10px;\n"
"    width: 10px;\n"
"    margin: 0px;\n"
"    border-radius: 5px;\n"
"}\n"
"QSlider::handle:vertical:hover {\n"
"    background-color: rgb(195, 155, 255);\n"
"}\n"
"QSlider::handle:vertical:pressed {\n"
"    background-color: rgb(255, 121, 198);\n"
"}\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"CommandLinkButton */\n"
"#pagesContainer QCommandLinkButton {\n"
"    color: rgb(255, 121, 198);\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"    border: 2px solid #ff79c6;\n"
"    color: #ff79c6;\n"
"}\n"
"#pagesContainer QCommandLinkButton:hover {\n"
"    color: rgb(255, 170, 255);\n"
"    background-color: #6272a4;\n"
"}\n"
"#pagesContainer QCommandLinkButton:pressed {\n"
"    color: rgb(189, 147, 249);\n"
"    background-color: #586796;\n"
"}\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"Button */\n"
"#pagesContainer QPushButton {\n"
"    border: 2px solid #6272a4;\n"
"    border-radius: 5px;\n"
"    background-color: #6272a4;\n"
"    color: #f8f8f2;\n"
"}\n"
"#pagesContainer QPushButton:hover {\n"
"    background-color: #7082b6;\n"
"    border: 2px solid #7082b6;\n"
"}\n"
"#pagesContainer QPushButton:pressed {\n"
"    background-color: #546391;\n"
"    border: 2px solid #ff79c6;\n"
"}")
        self.styleSheet.setObjectName("styleSheet")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.styleSheet)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.classApp = QtWidgets.QFrame(self.styleSheet)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.classApp.sizePolicy().hasHeightForWidth())
        self.classApp.setSizePolicy(sizePolicy)
        self.classApp.setStyleSheet("")
        self.classApp.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.classApp.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.classApp.setObjectName("classApp")
        self.appLayout = QtWidgets.QHBoxLayout(self.classApp)
        self.appLayout.setContentsMargins(0, 0, 0, 0)
        self.appLayout.setSpacing(0)
        self.appLayout.setObjectName("appLayout")
        self.leftMenuBg = QtWidgets.QFrame(self.classApp)
        self.leftMenuBg.setMinimumSize(QtCore.QSize(60, 0))
        self.leftMenuBg.setMaximumSize(QtCore.QSize(60, 16777215))
        self.leftMenuBg.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.leftMenuBg.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.leftMenuBg.setObjectName("leftMenuBg")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.leftMenuBg)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.topLogoInfo = QtWidgets.QFrame(self.leftMenuBg)
        self.topLogoInfo.setMinimumSize(QtCore.QSize(0, 50))
        self.topLogoInfo.setMaximumSize(QtCore.QSize(16777215, 50))
        self.topLogoInfo.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.topLogoInfo.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.topLogoInfo.setObjectName("topLogoInfo")
        self.topLogo = QtWidgets.QFrame(self.topLogoInfo)
        self.topLogo.setGeometry(QtCore.QRect(6, 0, 48, 48))
        self.topLogo.setMinimumSize(QtCore.QSize(48, 48))
        self.topLogo.setMaximumSize(QtCore.QSize(48, 48))
        self.topLogo.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.topLogo.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.topLogo.setObjectName("topLogo")
        self.titleLeftApp = QtWidgets.QLabel(self.topLogoInfo)
        self.titleLeftApp.setGeometry(QtCore.QRect(70, 8, 160, 20))
        font = QtGui.QFont()
        font.setFamily("SimHei Semibold")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        self.titleLeftApp.setFont(font)
        self.titleLeftApp.setAlignment(QtCore.Qt.Alignment.AlignLeading|QtCore.Qt.Alignment.AlignLeft|QtCore.Qt.Alignment.AlignTop)
        self.titleLeftApp.setObjectName("titleLeftApp")
        self.titleLeftDescription = QtWidgets.QLabel(self.topLogoInfo)
        self.titleLeftDescription.setGeometry(QtCore.QRect(70, 27, 160, 16))
        self.titleLeftDescription.setMaximumSize(QtCore.QSize(16777215, 16))
        font = QtGui.QFont()
        font.setFamily("SimHei")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        self.titleLeftDescription.setFont(font)
        self.titleLeftDescription.setAlignment(QtCore.Qt.Alignment.AlignLeading|QtCore.Qt.Alignment.AlignLeft|QtCore.Qt.Alignment.AlignTop)
        self.titleLeftDescription.setObjectName("titleLeftDescription")
        self.verticalLayout_3.addWidget(self.topLogoInfo)
        self.leftMenuFrame = QtWidgets.QFrame(self.leftMenuBg)
        self.leftMenuFrame.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.leftMenuFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.leftMenuFrame.setObjectName("leftMenuFrame")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.leftMenuFrame)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.toggleBox = QtWidgets.QFrame(self.leftMenuFrame)
        self.toggleBox.setMaximumSize(QtCore.QSize(16777215, 45))
        self.toggleBox.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.toggleBox.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.toggleBox.setObjectName("toggleBox")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.toggleBox)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.toggleButton = QtWidgets.QPushButton(self.toggleBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toggleButton.sizePolicy().hasHeightForWidth())
        self.toggleButton.setSizePolicy(sizePolicy)
        self.toggleButton.setMinimumSize(QtCore.QSize(0, 45))
        font = QtGui.QFont()
        font.setFamily("SimHei")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        self.toggleButton.setFont(font)
        self.toggleButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.toggleButton.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.toggleButton.setStyleSheet("background-image: url(:/icons/images/icons/icon_menu.png);")
        self.toggleButton.setObjectName("toggleButton")
        self.verticalLayout_4.addWidget(self.toggleButton)
        self.verticalLayout_7.addWidget(self.toggleBox)
        self.topMenu = QtWidgets.QFrame(self.leftMenuFrame)
        self.topMenu.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.topMenu.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.topMenu.setObjectName("topMenu")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.topMenu)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.btn_home = QtWidgets.QPushButton(self.topMenu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_home.sizePolicy().hasHeightForWidth())
        self.btn_home.setSizePolicy(sizePolicy)
        self.btn_home.setMinimumSize(QtCore.QSize(0, 45))
        font = QtGui.QFont()
        font.setFamily("SimHei")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        self.btn_home.setFont(font)
        self.btn_home.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_home.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.btn_home.setStyleSheet("background-image: url(:/icons/images/icons/cil-home.png);")
        self.btn_home.setObjectName("btn_home")
        self.verticalLayout_8.addWidget(self.btn_home)
        self.btn_graphic = QtWidgets.QPushButton(self.topMenu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_graphic.sizePolicy().hasHeightForWidth())
        self.btn_graphic.setSizePolicy(sizePolicy)
        self.btn_graphic.setMinimumSize(QtCore.QSize(0, 45))
        font = QtGui.QFont()
        font.setFamily("SimHei")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        self.btn_graphic.setFont(font)
        self.btn_graphic.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_graphic.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.btn_graphic.setStyleSheet("background-image: url(:/icons/images/icons/cil-map.png);")
        self.btn_graphic.setObjectName("btn_graphic")
        self.verticalLayout_8.addWidget(self.btn_graphic)
        self.btn_human = QtWidgets.QPushButton(self.topMenu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_human.sizePolicy().hasHeightForWidth())
        self.btn_human.setSizePolicy(sizePolicy)
        self.btn_human.setMinimumSize(QtCore.QSize(0, 45))
        font = QtGui.QFont()
        font.setFamily("SimHei")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        self.btn_human.setFont(font)
        self.btn_human.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_human.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.btn_human.setStyleSheet("background-image: url(:/icons/images/icons/cil-user.png);")
        self.btn_human.setObjectName("btn_human")
        self.verticalLayout_8.addWidget(self.btn_human)
        self.btn_look = QtWidgets.QPushButton(self.topMenu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_look.sizePolicy().hasHeightForWidth())
        self.btn_look.setSizePolicy(sizePolicy)
        self.btn_look.setMinimumSize(QtCore.QSize(0, 45))
        font = QtGui.QFont()
        font.setFamily("SimHei")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        self.btn_look.setFont(font)
        self.btn_look.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_look.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.btn_look.setStyleSheet("background-image: url(:/icons/images/icons/cil-calendar-check.png)")
        self.btn_look.setObjectName("btn_look")
        self.verticalLayout_8.addWidget(self.btn_look)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_8.addItem(spacerItem)
        self.verticalLayout_7.addWidget(self.topMenu)
        self.bottomMenu = QtWidgets.QFrame(self.leftMenuFrame)
        self.bottomMenu.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.bottomMenu.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.bottomMenu.setObjectName("bottomMenu")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.bottomMenu)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.toggleLeftBox = QtWidgets.QPushButton(self.bottomMenu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toggleLeftBox.sizePolicy().hasHeightForWidth())
        self.toggleLeftBox.setSizePolicy(sizePolicy)
        self.toggleLeftBox.setMinimumSize(QtCore.QSize(0, 45))
        font = QtGui.QFont()
        font.setFamily("SimHei")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        self.toggleLeftBox.setFont(font)
        self.toggleLeftBox.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.toggleLeftBox.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.toggleLeftBox.setStyleSheet("background-image: url(:/icons/images/icons/cil-options-horizontal.png);")
        self.toggleLeftBox.setObjectName("toggleLeftBox")
        self.verticalLayout_9.addWidget(self.toggleLeftBox)
        self.verticalLayout_7.addWidget(self.bottomMenu)
        self.verticalLayout_3.addWidget(self.leftMenuFrame)
        self.appLayout.addWidget(self.leftMenuBg)
        self.extraLeftBox = QtWidgets.QFrame(self.classApp)
        self.extraLeftBox.setMinimumSize(QtCore.QSize(0, 0))
        self.extraLeftBox.setMaximumSize(QtCore.QSize(0, 16777215))
        self.extraLeftBox.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.extraLeftBox.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.extraLeftBox.setObjectName("extraLeftBox")
        self.extraColumLayout = QtWidgets.QVBoxLayout(self.extraLeftBox)
        self.extraColumLayout.setContentsMargins(0, 0, 0, 0)
        self.extraColumLayout.setSpacing(0)
        self.extraColumLayout.setObjectName("extraColumLayout")
        self.extraTopBg = QtWidgets.QFrame(self.extraLeftBox)
        self.extraTopBg.setMinimumSize(QtCore.QSize(0, 50))
        self.extraTopBg.setMaximumSize(QtCore.QSize(16777215, 50))
        self.extraTopBg.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.extraTopBg.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.extraTopBg.setObjectName("extraTopBg")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.extraTopBg)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.extraTopLayout = QtWidgets.QGridLayout()
        self.extraTopLayout.setContentsMargins(10, -1, 10, -1)
        self.extraTopLayout.setHorizontalSpacing(10)
        self.extraTopLayout.setVerticalSpacing(0)
        self.extraTopLayout.setObjectName("extraTopLayout")
        self.extraIcon = QtWidgets.QFrame(self.extraTopBg)
        self.extraIcon.setMinimumSize(QtCore.QSize(20, 0))
        self.extraIcon.setMaximumSize(QtCore.QSize(20, 20))
        self.extraIcon.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.extraIcon.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.extraIcon.setObjectName("extraIcon")
        self.extraTopLayout.addWidget(self.extraIcon, 0, 0, 1, 1)
        self.extraLabel = QtWidgets.QLabel(self.extraTopBg)
        self.extraLabel.setMinimumSize(QtCore.QSize(150, 0))
        self.extraLabel.setObjectName("extraLabel")
        self.extraTopLayout.addWidget(self.extraLabel, 0, 1, 1, 1)
        self.extraCloseColumnBtn = QtWidgets.QPushButton(self.extraTopBg)
        self.extraCloseColumnBtn.setMinimumSize(QtCore.QSize(28, 28))
        self.extraCloseColumnBtn.setMaximumSize(QtCore.QSize(28, 28))
        self.extraCloseColumnBtn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.extraCloseColumnBtn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/images/icons/icon_close.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.extraCloseColumnBtn.setIcon(icon)
        self.extraCloseColumnBtn.setIconSize(QtCore.QSize(20, 20))
        self.extraCloseColumnBtn.setObjectName("extraCloseColumnBtn")
        self.extraTopLayout.addWidget(self.extraCloseColumnBtn, 0, 2, 1, 1)
        self.verticalLayout_5.addLayout(self.extraTopLayout)
        self.extraColumLayout.addWidget(self.extraTopBg)
        self.extraContent = QtWidgets.QFrame(self.extraLeftBox)
        self.extraContent.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.extraContent.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.extraContent.setObjectName("extraContent")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.extraContent)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setSpacing(0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.extraTopMenu = QtWidgets.QFrame(self.extraContent)
        self.extraTopMenu.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.extraTopMenu.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.extraTopMenu.setObjectName("extraTopMenu")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.extraTopMenu)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.btn_heart = QtWidgets.QPushButton(self.extraTopMenu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_heart.sizePolicy().hasHeightForWidth())
        self.btn_heart.setSizePolicy(sizePolicy)
        self.btn_heart.setMinimumSize(QtCore.QSize(0, 45))
        font = QtGui.QFont()
        font.setFamily("SimHei")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        self.btn_heart.setFont(font)
        self.btn_heart.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_heart.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.btn_heart.setStyleSheet("background-image: url(:/icons/images/icons/cil-heart.png);")
        self.btn_heart.setObjectName("btn_heart")
        self.verticalLayout_11.addWidget(self.btn_heart)
        self.btn_out = QtWidgets.QPushButton(self.extraTopMenu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_out.sizePolicy().hasHeightForWidth())
        self.btn_out.setSizePolicy(sizePolicy)
        self.btn_out.setMinimumSize(QtCore.QSize(0, 45))
        font = QtGui.QFont()
        font.setFamily("SimHei")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        self.btn_out.setFont(font)
        self.btn_out.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_out.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.btn_out.setStyleSheet("background-image: url(:/icons/images/icons/cil-account-logout.png);")
        self.btn_out.setObjectName("btn_out")
        self.verticalLayout_11.addWidget(self.btn_out)
        self.btn_refer = QtWidgets.QPushButton(self.extraTopMenu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_refer.sizePolicy().hasHeightForWidth())
        self.btn_refer.setSizePolicy(sizePolicy)
        self.btn_refer.setMinimumSize(QtCore.QSize(0, 45))
        font = QtGui.QFont()
        font.setFamily("SimHei")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        self.btn_refer.setFont(font)
        self.btn_refer.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_refer.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.btn_refer.setStyleSheet("background-image: url(:/icons/images/icons/cil-layers.png);")
        self.btn_refer.setObjectName("btn_refer")
        self.verticalLayout_11.addWidget(self.btn_refer)
        self.verticalLayout_12.addWidget(self.extraTopMenu, 0, QtCore.Qt.AlignTop)
        self.extraCenter = QtWidgets.QFrame(self.extraContent)
        self.extraCenter.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.extraCenter.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.extraCenter.setObjectName("extraCenter")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.extraCenter)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setSpacing(0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.extraTextEdit = QtWidgets.QTextEdit(self.extraCenter)
        self.extraTextEdit.setMinimumSize(QtCore.QSize(222, 0))
        self.extraTextEdit.setStyleSheet("background: transparent;")
        self.extraTextEdit.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.extraTextEdit.setReadOnly(True)
        self.extraTextEdit.setObjectName("extraTextEdit")
        self.verticalLayout_10.addWidget(self.extraTextEdit)
        self.verticalLayout_12.addWidget(self.extraCenter)
        self.extraColumLayout.addWidget(self.extraContent)
        self.appLayout.addWidget(self.extraLeftBox)
        self.contentBox = QtWidgets.QFrame(self.classApp)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.contentBox.sizePolicy().hasHeightForWidth())
        self.contentBox.setSizePolicy(sizePolicy)
        self.contentBox.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.contentBox.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.contentBox.setObjectName("contentBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.contentBox)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.contentTopBg = QtWidgets.QFrame(self.contentBox)
        self.contentTopBg.setMinimumSize(QtCore.QSize(0, 50))
        self.contentTopBg.setMaximumSize(QtCore.QSize(16777215, 50))
        self.contentTopBg.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.contentTopBg.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.contentTopBg.setObjectName("contentTopBg")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.contentTopBg)
        self.horizontalLayout.setContentsMargins(0, 0, 10, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.leftBox = QtWidgets.QFrame(self.contentTopBg)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leftBox.sizePolicy().hasHeightForWidth())
        self.leftBox.setSizePolicy(sizePolicy)
        self.leftBox.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.leftBox.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.leftBox.setObjectName("leftBox")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.leftBox)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.titleRightInfo = QtWidgets.QLabel(self.leftBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.titleRightInfo.sizePolicy().hasHeightForWidth())
        self.titleRightInfo.setSizePolicy(sizePolicy)
        self.titleRightInfo.setMaximumSize(QtCore.QSize(16777215, 500))
        font = QtGui.QFont()
        font.setFamily("SimHei")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        self.titleRightInfo.setFont(font)
        self.titleRightInfo.setAlignment(QtCore.Qt.Alignment.AlignLeading|QtCore.Qt.Alignment.AlignLeft|QtCore.Qt.Alignment.AlignVCenter)
        self.titleRightInfo.setObjectName("titleRightInfo")
        self.horizontalLayout_3.addWidget(self.titleRightInfo)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.horizontalLayout.addWidget(self.leftBox)
        self.rightButtons = QtWidgets.QFrame(self.contentTopBg)
        self.rightButtons.setMinimumSize(QtCore.QSize(0, 28))
        self.rightButtons.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.rightButtons.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.rightButtons.setObjectName("rightButtons")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.rightButtons)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(5)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.colorTopBtn = QtWidgets.QPushButton(self.rightButtons)
        self.colorTopBtn.setMinimumSize(QtCore.QSize(28, 28))
        self.colorTopBtn.setMaximumSize(QtCore.QSize(28, 28))
        self.colorTopBtn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.colorTopBtn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/images/icons/cil-lightbulb.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.colorTopBtn.setIcon(icon1)
        self.colorTopBtn.setIconSize(QtCore.QSize(20, 20))
        self.colorTopBtn.setObjectName("colorTopBtn")
        self.horizontalLayout_2.addWidget(self.colorTopBtn)
        self.minimizeAppBtn = QtWidgets.QPushButton(self.rightButtons)
        self.minimizeAppBtn.setMinimumSize(QtCore.QSize(28, 28))
        self.minimizeAppBtn.setMaximumSize(QtCore.QSize(28, 28))
        self.minimizeAppBtn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.minimizeAppBtn.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/images/icons/icon_minimize.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.minimizeAppBtn.setIcon(icon2)
        self.minimizeAppBtn.setIconSize(QtCore.QSize(20, 20))
        self.minimizeAppBtn.setObjectName("minimizeAppBtn")
        self.horizontalLayout_2.addWidget(self.minimizeAppBtn)
        self.maximizeRestoreAppBtn = QtWidgets.QPushButton(self.rightButtons)
        self.maximizeRestoreAppBtn.setMinimumSize(QtCore.QSize(28, 28))
        self.maximizeRestoreAppBtn.setMaximumSize(QtCore.QSize(28, 28))
        font = QtGui.QFont()
        font.setFamily("SimHei")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setStyleStrategy(QtGui.QFont.StyleStrategy.PreferDefault)
        self.maximizeRestoreAppBtn.setFont(font)
        self.maximizeRestoreAppBtn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.maximizeRestoreAppBtn.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/images/icons/icon_maximize.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.maximizeRestoreAppBtn.setIcon(icon3)
        self.maximizeRestoreAppBtn.setIconSize(QtCore.QSize(20, 20))
        self.maximizeRestoreAppBtn.setObjectName("maximizeRestoreAppBtn")
        self.horizontalLayout_2.addWidget(self.maximizeRestoreAppBtn)
        self.closeAppBtn = QtWidgets.QPushButton(self.rightButtons)
        self.closeAppBtn.setMinimumSize(QtCore.QSize(28, 28))
        self.closeAppBtn.setMaximumSize(QtCore.QSize(28, 28))
        self.closeAppBtn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.closeAppBtn.setText("")
        self.closeAppBtn.setIcon(icon)
        self.closeAppBtn.setIconSize(QtCore.QSize(20, 20))
        self.closeAppBtn.setObjectName("closeAppBtn")
        self.horizontalLayout_2.addWidget(self.closeAppBtn)
        self.horizontalLayout.addWidget(self.rightButtons, 0, QtCore.Qt.AlignRight)
        self.verticalLayout_2.addWidget(self.contentTopBg)
        self.contentBottom = QtWidgets.QFrame(self.contentBox)
        self.contentBottom.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.contentBottom.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.contentBottom.setObjectName("contentBottom")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.contentBottom)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.content = QtWidgets.QFrame(self.contentBottom)
        self.content.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.content.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.content.setObjectName("content")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.content)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pagesContainer = QtWidgets.QFrame(self.content)
        self.pagesContainer.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.pagesContainer.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.pagesContainer.setObjectName("pagesContainer")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.pagesContainer)
        self.verticalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_15.setSpacing(0)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.pagesContainer_2 = QtWidgets.QFrame(self.pagesContainer)
        self.pagesContainer_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.pagesContainer_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.pagesContainer_2.setObjectName("pagesContainer_2")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.pagesContainer_2)
        self.verticalLayout_16.setContentsMargins(9, 9, 9, 9)
        self.verticalLayout_16.setSpacing(9)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.myStackedWidget = QtWidgets.QStackedWidget(self.pagesContainer_2)
        self.myStackedWidget.setStyleSheet("background: transparent;")
        self.myStackedWidget.setObjectName("myStackedWidget")
        self.page_1 = QtWidgets.QWidget()
        self.page_1.setObjectName("page_1")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.page_1)
        self.verticalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_18.setSpacing(0)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.page1Up = QtWidgets.QFrame(self.page_1)
        self.page1Up.setMaximumSize(QtCore.QSize(16777215, 14444444))
        self.page1Up.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.page1Up.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.page1Up.setObjectName("page1Up")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.page1Up)
        self.verticalLayout_19.setContentsMargins(-1, -1, -1, 0)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.page1ChooseFile = QtWidgets.QFrame(self.page1Up)
        self.page1ChooseFile.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.page1ChooseFile.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.page1ChooseFile.setObjectName("page1ChooseFile")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.page1ChooseFile)
        self.verticalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_14.setSpacing(10)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.page1ChooseFileLabel = QtWidgets.QLabel(self.page1ChooseFile)
        self.page1ChooseFileLabel.setStyleSheet("color: rgb(113, 126, 149);")
        self.page1ChooseFileLabel.setObjectName("page1ChooseFileLabel")
        self.verticalLayout_14.addWidget(self.page1ChooseFileLabel)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.page1ChooseFileLineEdit = QtWidgets.QLineEdit(self.page1ChooseFile)
        self.page1ChooseFileLineEdit.setMinimumSize(QtCore.QSize(0, 30))
        self.page1ChooseFileLineEdit.setStyleSheet("")
        self.page1ChooseFileLineEdit.setObjectName("page1ChooseFileLineEdit")
        self.horizontalLayout_12.addWidget(self.page1ChooseFileLineEdit)
        self.page1ChooseFileBtn = QtWidgets.QPushButton(self.page1ChooseFile)
        self.page1ChooseFileBtn.setMinimumSize(QtCore.QSize(150, 30))
        font = QtGui.QFont()
        font.setFamily("SimHei")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        self.page1ChooseFileBtn.setFont(font)
        self.page1ChooseFileBtn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.page1ChooseFileBtn.setStyleSheet("\n"
"background-color: #6272a4;")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/images/icons/cil-folder-open.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.page1ChooseFileBtn.setIcon(icon4)
        self.page1ChooseFileBtn.setObjectName("page1ChooseFileBtn")
        self.horizontalLayout_12.addWidget(self.page1ChooseFileBtn)
        self.verticalLayout_14.addLayout(self.horizontalLayout_12)
        self.verticalLayout_19.addWidget(self.page1ChooseFile)
        self.page1ChooseOther = QtWidgets.QFrame(self.page1Up)
        self.page1ChooseOther.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.page1ChooseOther.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.page1ChooseOther.setObjectName("page1ChooseOther")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.page1ChooseOther)
        self.horizontalLayout_6.setContentsMargins(0, 10, 0, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.page1ChooseMajorLabel = QtWidgets.QLabel(self.page1ChooseOther)
        self.page1ChooseMajorLabel.setStyleSheet("color: rgb(113, 126, 149);")
        self.page1ChooseMajorLabel.setObjectName("page1ChooseMajorLabel")
        self.horizontalLayout_6.addWidget(self.page1ChooseMajorLabel)
        self.page1ChooseMajorComboBox = QtWidgets.QComboBox(self.page1ChooseOther)
        self.page1ChooseMajorComboBox.setMinimumSize(QtCore.QSize(150, 0))
        self.page1ChooseMajorComboBox.setStyleSheet("\n"
"background-color: #6272a4;")
        self.page1ChooseMajorComboBox.setObjectName("page1ChooseMajorComboBox")
        self.page1ChooseMajorComboBox.addItem("")
        self.page1ChooseMajorComboBox.addItem("")
        self.page1ChooseMajorComboBox.addItem("")
        self.horizontalLayout_6.addWidget(self.page1ChooseMajorComboBox)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem2)
        self.page1ChooseClassLabel = QtWidgets.QLabel(self.page1ChooseOther)
        self.page1ChooseClassLabel.setStyleSheet("color: rgb(113, 126, 149);")
        self.page1ChooseClassLabel.setObjectName("page1ChooseClassLabel")
        self.horizontalLayout_6.addWidget(self.page1ChooseClassLabel)
        self.page1ChooseClassLineEdit = QtWidgets.QLineEdit(self.page1ChooseOther)
        self.page1ChooseClassLineEdit.setMinimumSize(QtCore.QSize(0, 31))
        self.page1ChooseClassLineEdit.setStyleSheet("")
        self.page1ChooseClassLineEdit.setObjectName("page1ChooseClassLineEdit")
        self.horizontalLayout_6.addWidget(self.page1ChooseClassLineEdit)
        self.verticalLayout_19.addWidget(self.page1ChooseOther)
        self.verticalLayout_18.addWidget(self.page1Up)
        self.page1Down = QtWidgets.QFrame(self.page_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.page1Down.sizePolicy().hasHeightForWidth())
        self.page1Down.setSizePolicy(sizePolicy)
        self.page1Down.setMinimumSize(QtCore.QSize(0, 0))
        self.page1Down.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.page1Down.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.page1Down.setObjectName("page1Down")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.page1Down)
        self.verticalLayout_21.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_21.setSpacing(0)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.page1TableWidget = QtWidgets.QTableWidget(self.page1Down)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.page1TableWidget.sizePolicy().hasHeightForWidth())
        self.page1TableWidget.setSizePolicy(sizePolicy)
        self.page1TableWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.page1TableWidget.setFocusPolicy(QtCore.Qt.FocusPolicy.WheelFocus)
        self.page1TableWidget.setStyleSheet("")
        self.page1TableWidget.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.page1TableWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOn)
        self.page1TableWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.SizeAdjustPolicy.AdjustToContents)
        self.page1TableWidget.setAutoScroll(True)
        self.page1TableWidget.setEditTriggers(QtWidgets.QAbstractItemView.EditTriggers.NoEditTriggers)
        self.page1TableWidget.setProperty("showDropIndicator", True)
        self.page1TableWidget.setDragEnabled(True)
        self.page1TableWidget.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.SingleSelection)
        self.page1TableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.page1TableWidget.setShowGrid(True)
        self.page1TableWidget.setGridStyle(QtCore.Qt.PenStyle.CustomDashLine)
        self.page1TableWidget.setCornerButtonEnabled(True)
        self.page1TableWidget.setRowCount(50)
        self.page1TableWidget.setObjectName("page1TableWidget")
        self.page1TableWidget.setColumnCount(5)
        item = QtWidgets.QTableWidgetItem()
        self.page1TableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.page1TableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.page1TableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.page1TableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.page1TableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.page1TableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.page1TableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.page1TableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.page1TableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.page1TableWidget.setHorizontalHeaderItem(4, item)
        self.page1TableWidget.horizontalHeader().setVisible(True)
        self.page1TableWidget.horizontalHeader().setCascadingSectionResizes(True)
        self.page1TableWidget.horizontalHeader().setDefaultSectionSize(100)
        self.page1TableWidget.horizontalHeader().setHighlightSections(True)
        self.page1TableWidget.horizontalHeader().setMinimumSectionSize(20)
        self.page1TableWidget.horizontalHeader().setStretchLastSection(True)
        self.page1TableWidget.verticalHeader().setVisible(False)
        self.page1TableWidget.verticalHeader().setDefaultSectionSize(30)
        self.page1TableWidget.verticalHeader().setHighlightSections(False)
        self.page1TableWidget.verticalHeader().setStretchLastSection(True)
        self.verticalLayout_21.addWidget(self.page1TableWidget)
        self.verticalLayout_18.addWidget(self.page1Down)
        self.myStackedWidget.addWidget(self.page_1)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.page_2)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.frame_2 = QtWidgets.QFrame(self.page_2)
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_3.setMaximumSize(QtCore.QSize(280, 16777215))
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.page2TableWidget = QtWidgets.QTableWidget(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.page2TableWidget.sizePolicy().hasHeightForWidth())
        self.page2TableWidget.setSizePolicy(sizePolicy)
        self.page2TableWidget.setMinimumSize(QtCore.QSize(280, 0))
        self.page2TableWidget.setMaximumSize(QtCore.QSize(300, 16777215))
        self.page2TableWidget.setStyleSheet("QTabelWidget:: item::selected\n"
"{\n"
"    background:rgb(170, 170, 255)\n"
"}\n"
"")
        self.page2TableWidget.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.page2TableWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOn)
        self.page2TableWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.page2TableWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.SizeAdjustPolicy.AdjustToContents)
        self.page2TableWidget.setEditTriggers(QtWidgets.QAbstractItemView.EditTriggers.NoEditTriggers)
        self.page2TableWidget.setDragEnabled(True)
        self.page2TableWidget.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.SingleSelection)
        self.page2TableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.page2TableWidget.setGridStyle(QtCore.Qt.PenStyle.CustomDashLine)
        self.page2TableWidget.setRowCount(50)
        self.page2TableWidget.setObjectName("page2TableWidget")
        self.page2TableWidget.setColumnCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.page2TableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.page2TableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.page2TableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.page2TableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.page2TableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.page2TableWidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.page2TableWidget.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.page2TableWidget.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.page2TableWidget.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.page2TableWidget.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.page2TableWidget.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.page2TableWidget.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.page2TableWidget.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.page2TableWidget.setVerticalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.page2TableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.page2TableWidget.setHorizontalHeaderItem(1, item)
        self.page2TableWidget.horizontalHeader().setCascadingSectionResizes(True)
        self.page2TableWidget.horizontalHeader().setDefaultSectionSize(130)
        self.page2TableWidget.horizontalHeader().setMinimumSectionSize(20)
        self.page2TableWidget.horizontalHeader().setSortIndicatorShown(False)
        self.page2TableWidget.horizontalHeader().setStretchLastSection(True)
        self.page2TableWidget.verticalHeader().setVisible(False)
        self.page2TableWidget.verticalHeader().setCascadingSectionResizes(False)
        self.page2TableWidget.verticalHeader().setDefaultSectionSize(30)
        self.page2TableWidget.verticalHeader().setHighlightSections(False)
        self.page2TableWidget.verticalHeader().setMinimumSectionSize(10)
        self.page2TableWidget.verticalHeader().setStretchLastSection(True)
        self.horizontalLayout_9.addWidget(self.page2TableWidget)
        self.horizontalLayout_8.addWidget(self.frame_3)
        self.frame_4 = QtWidgets.QFrame(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_4.sizePolicy().hasHeightForWidth())
        self.frame_4.setSizePolicy(sizePolicy)
        self.frame_4.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_22.setContentsMargins(20, 0, 20, 0)
        self.verticalLayout_22.setSpacing(0)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.label = QtWidgets.QLabel(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(0, 0))
        self.label.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label.setStyleSheet("border: 2px solid #6272a4;")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/images/images/images/PyDracula_vertical.png"))
        self.label.setAlignment(QtCore.Qt.Alignment.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_22.addWidget(self.label)
        self.frame_5 = QtWidgets.QFrame(self.frame_4)
        self.frame_5.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_4.setContentsMargins(0, 5, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.clearPhotoBtn = QtWidgets.QPushButton(self.frame_5)
        self.clearPhotoBtn.setMinimumSize(QtCore.QSize(150, 30))
        font = QtGui.QFont()
        font.setFamily("SimHei")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        self.clearPhotoBtn.setFont(font)
        self.clearPhotoBtn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.clearPhotoBtn.setStyleSheet("\n"
"background-color: #6272a4;")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/images/icons/cil-low-vision.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.clearPhotoBtn.setIcon(icon5)
        self.clearPhotoBtn.setObjectName("clearPhotoBtn")
        self.horizontalLayout_4.addWidget(self.clearPhotoBtn)
        spacerItem3 = QtWidgets.QSpacerItem(60, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.reloadPhotoBtn = QtWidgets.QPushButton(self.frame_5)
        self.reloadPhotoBtn.setMinimumSize(QtCore.QSize(150, 30))
        font = QtGui.QFont()
        font.setFamily("SimHei")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        self.reloadPhotoBtn.setFont(font)
        self.reloadPhotoBtn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.reloadPhotoBtn.setStyleSheet("\n"
"background-color: #6272a4;")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/images/icons/cil-loop-circular.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.reloadPhotoBtn.setIcon(icon6)
        self.reloadPhotoBtn.setObjectName("reloadPhotoBtn")
        self.horizontalLayout_4.addWidget(self.reloadPhotoBtn)
        self.verticalLayout_22.addWidget(self.frame_5)
        self.horizontalLayout_8.addWidget(self.frame_4)
        self.horizontalLayout_7.addWidget(self.frame_2)
        self.myStackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.page_3.sizePolicy().hasHeightForWidth())
        self.page_3.setSizePolicy(sizePolicy)
        self.page_3.setObjectName("page_3")
        self.verticalLayout_23 = QtWidgets.QVBoxLayout(self.page_3)
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.frame = QtWidgets.QFrame(self.page_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_14.setSpacing(0)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.frame_6 = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_6.sizePolicy().hasHeightForWidth())
        self.frame_6.setSizePolicy(sizePolicy)
        self.frame_6.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_6.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_24 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_24.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_24.setSpacing(0)
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.page3InfoLabel_2 = QtWidgets.QLabel(self.frame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.page3InfoLabel_2.sizePolicy().hasHeightForWidth())
        self.page3InfoLabel_2.setSizePolicy(sizePolicy)
        self.page3InfoLabel_2.setMinimumSize(QtCore.QSize(0, 30))
        self.page3InfoLabel_2.setMaximumSize(QtCore.QSize(16777215, 30))
        self.page3InfoLabel_2.setStyleSheet("color: rgb(113, 126, 149);")
        self.page3InfoLabel_2.setObjectName("page3InfoLabel_2")
        self.verticalLayout_24.addWidget(self.page3InfoLabel_2)
        self.graphicsView = QtWidgets.QGraphicsView(self.frame_6)
        self.graphicsView.setMinimumSize(QtCore.QSize(0, 1))
        self.graphicsView.setMaximumSize(QtCore.QSize(16777215, 1))
        self.graphicsView.setStyleSheet("background-color: #6272a4;")
        self.graphicsView.setObjectName("graphicsView")
        self.verticalLayout_24.addWidget(self.graphicsView)
        self.web_browser_widget = QtWidgets.QWidget(self.frame_6)
        self.web_browser_widget.setObjectName("web_browser_widget")
        self.verticalLayout_24.addWidget(self.web_browser_widget)
        self.horizontalLayout_14.addWidget(self.frame_6)
        self.verticalLayout_23.addWidget(self.frame)
        self.frame_8 = QtWidgets.QFrame(self.page_3)
        self.frame_8.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_23.addWidget(self.frame_8)
        self.myStackedWidget.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.page_4)
        self.verticalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_17.setSpacing(0)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.page4All = QtWidgets.QFrame(self.page_4)
        self.page4All.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.page4All.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.page4All.setObjectName("page4All")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.page4All)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.page4Up = QtWidgets.QFrame(self.page4All)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.page4Up.sizePolicy().hasHeightForWidth())
        self.page4Up.setSizePolicy(sizePolicy)
        self.page4Up.setMinimumSize(QtCore.QSize(0, 50))
        self.page4Up.setMaximumSize(QtCore.QSize(16777215, 166666))
        self.page4Up.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.page4Up.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.page4Up.setObjectName("page4Up")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.page4Up)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.page4AdjustLabel = QtWidgets.QLabel(self.page4Up)
        self.page4AdjustLabel.setStyleSheet("color: rgb(113, 126, 149);")
        self.page4AdjustLabel.setObjectName("page4AdjustLabel")
        self.horizontalLayout_11.addWidget(self.page4AdjustLabel)
        self.page4AdjustLinetext = QtWidgets.QLineEdit(self.page4Up)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.page4AdjustLinetext.sizePolicy().hasHeightForWidth())
        self.page4AdjustLinetext.setSizePolicy(sizePolicy)
        self.page4AdjustLinetext.setMinimumSize(QtCore.QSize(180, 30))
        self.page4AdjustLinetext.setStyleSheet("")
        self.page4AdjustLinetext.setText("")
        self.page4AdjustLinetext.setObjectName("page4AdjustLinetext")
        self.horizontalLayout_11.addWidget(self.page4AdjustLinetext)
        self.page4LeftBtn = QtWidgets.QPushButton(self.page4Up)
        self.page4LeftBtn.setMinimumSize(QtCore.QSize(30, 30))
        self.page4LeftBtn.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setFamily("SimHei")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        self.page4LeftBtn.setFont(font)
        self.page4LeftBtn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.page4LeftBtn.setStyleSheet("\n"
"background-color: #6272a4;")
        self.page4LeftBtn.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/images/icons/cil-caret-left.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.page4LeftBtn.setIcon(icon7)
        self.page4LeftBtn.setObjectName("page4LeftBtn")
        self.horizontalLayout_11.addWidget(self.page4LeftBtn)
        self.page4RightBtn = QtWidgets.QPushButton(self.page4Up)
        self.page4RightBtn.setMinimumSize(QtCore.QSize(30, 30))
        self.page4RightBtn.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setFamily("SimHei")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        self.page4RightBtn.setFont(font)
        self.page4RightBtn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.page4RightBtn.setStyleSheet("\n"
"background-color: #6272a4;")
        self.page4RightBtn.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icons/images/icons/cil-caret-right.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.page4RightBtn.setIcon(icon8)
        self.page4RightBtn.setObjectName("page4RightBtn")
        self.horizontalLayout_11.addWidget(self.page4RightBtn)
        spacerItem4 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem4)
        self.page4XueShiLinetext = QtWidgets.QLineEdit(self.page4Up)
        self.page4XueShiLinetext.setMinimumSize(QtCore.QSize(210, 30))
        self.page4XueShiLinetext.setStyleSheet("")
        self.page4XueShiLinetext.setText("")
        self.page4XueShiLinetext.setObjectName("page4XueShiLinetext")
        self.horizontalLayout_11.addWidget(self.page4XueShiLinetext)
        self.page4XueShiBtn = QtWidgets.QPushButton(self.page4Up)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(30)
        sizePolicy.setHeightForWidth(self.page4XueShiBtn.sizePolicy().hasHeightForWidth())
        self.page4XueShiBtn.setSizePolicy(sizePolicy)
        self.page4XueShiBtn.setMinimumSize(QtCore.QSize(40, 30))
        self.page4XueShiBtn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.page4XueShiBtn.setStyleSheet("\n"
"background-color: #6272a4;")
        self.page4XueShiBtn.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/icons/images/icons/cil-equalizer.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.page4XueShiBtn.setIcon(icon9)
        self.page4XueShiBtn.setObjectName("page4XueShiBtn")
        self.horizontalLayout_11.addWidget(self.page4XueShiBtn)
        spacerItem5 = QtWidgets.QSpacerItem(313, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem5)
        self.page4PngBtn = QtWidgets.QPushButton(self.page4Up)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(30)
        sizePolicy.setHeightForWidth(self.page4PngBtn.sizePolicy().hasHeightForWidth())
        self.page4PngBtn.setSizePolicy(sizePolicy)
        self.page4PngBtn.setMinimumSize(QtCore.QSize(140, 30))
        self.page4PngBtn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.page4PngBtn.setStyleSheet("\n"
"background-color: #6272a4;")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/icons/images/icons/cil-print.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.page4PngBtn.setIcon(icon10)
        self.page4PngBtn.setObjectName("page4PngBtn")
        self.horizontalLayout_11.addWidget(self.page4PngBtn)
        self.verticalLayout_13.addWidget(self.page4Up)
        self.page4TableWidget = QtWidgets.QTableWidget(self.page4All)
        self.page4TableWidget.setFocusPolicy(QtCore.Qt.FocusPolicy.WheelFocus)
        self.page4TableWidget.setStyleSheet("QTabelWidget:: item::selected\n"
"{\n"
"    background:rgb(170, 170, 255)\n"
"}\n"
"")
        self.page4TableWidget.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.page4TableWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOn)
        self.page4TableWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.SizeAdjustPolicy.AdjustToContentsOnFirstShow)
        self.page4TableWidget.setAutoScroll(True)
        self.page4TableWidget.setAutoScrollMargin(5)
        self.page4TableWidget.setEditTriggers(QtWidgets.QAbstractItemView.EditTriggers.NoEditTriggers)
        self.page4TableWidget.setTabKeyNavigation(True)
        self.page4TableWidget.setProperty("showDropIndicator", True)
        self.page4TableWidget.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.SingleSelection)
        self.page4TableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectColumns)
        self.page4TableWidget.setTextElideMode(QtCore.Qt.TextElideMode.ElideRight)
        self.page4TableWidget.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollMode.ScrollPerItem)
        self.page4TableWidget.setRowCount(50)
        self.page4TableWidget.setColumnCount(8)
        self.page4TableWidget.setObjectName("page4TableWidget")
        item = QtWidgets.QTableWidgetItem()
        self.page4TableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.page4TableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.page4TableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.page4TableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.page4TableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.page4TableWidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.page4TableWidget.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.page4TableWidget.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.page4TableWidget.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.page4TableWidget.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.page4TableWidget.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.page4TableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.page4TableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.page4TableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.page4TableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.page4TableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.page4TableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.page4TableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.page4TableWidget.setHorizontalHeaderItem(7, item)
        self.page4TableWidget.horizontalHeader().setVisible(True)
        self.page4TableWidget.horizontalHeader().setCascadingSectionResizes(True)
        self.page4TableWidget.horizontalHeader().setDefaultSectionSize(98)
        self.page4TableWidget.horizontalHeader().setHighlightSections(True)
        self.page4TableWidget.horizontalHeader().setMinimumSectionSize(35)
        self.page4TableWidget.horizontalHeader().setStretchLastSection(True)
        self.page4TableWidget.verticalHeader().setVisible(False)
        self.page4TableWidget.verticalHeader().setDefaultSectionSize(30)
        self.page4TableWidget.verticalHeader().setHighlightSections(False)
        self.page4TableWidget.verticalHeader().setMinimumSectionSize(10)
        self.page4TableWidget.verticalHeader().setSortIndicatorShown(False)
        self.page4TableWidget.verticalHeader().setStretchLastSection(True)
        self.verticalLayout_13.addWidget(self.page4TableWidget)
        self.verticalLayout_17.addWidget(self.page4All)
        self.myStackedWidget.addWidget(self.page_4)
        self.verticalLayout_16.addWidget(self.myStackedWidget)
        self.verticalLayout_15.addWidget(self.pagesContainer_2)
        self.verticalLayout.addWidget(self.pagesContainer)
        self.verticalLayout_6.addWidget(self.content)
        self.bottomBar = QtWidgets.QFrame(self.contentBottom)
        self.bottomBar.setMinimumSize(QtCore.QSize(0, 22))
        self.bottomBar.setMaximumSize(QtCore.QSize(16777215, 22))
        self.bottomBar.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.bottomBar.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.bottomBar.setObjectName("bottomBar")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.bottomBar)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.writerLabel = QtWidgets.QLabel(self.bottomBar)
        self.writerLabel.setMaximumSize(QtCore.QSize(16777215, 16))
        font = QtGui.QFont()
        font.setFamily("SimHei")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        self.writerLabel.setFont(font)
        self.writerLabel.setAlignment(QtCore.Qt.Alignment.AlignLeading|QtCore.Qt.Alignment.AlignLeft|QtCore.Qt.Alignment.AlignVCenter)
        self.writerLabel.setObjectName("writerLabel")
        self.horizontalLayout_5.addWidget(self.writerLabel)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem6)
        self.version = QtWidgets.QLabel(self.bottomBar)
        font = QtGui.QFont()
        font.setFamily("SimHei")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        self.version.setFont(font)
        self.version.setAlignment(QtCore.Qt.Alignment.AlignRight|QtCore.Qt.Alignment.AlignTrailing|QtCore.Qt.Alignment.AlignVCenter)
        self.version.setObjectName("version")
        self.horizontalLayout_5.addWidget(self.version)
        self.frame_size_grip = QtWidgets.QFrame(self.bottomBar)
        self.frame_size_grip.setMinimumSize(QtCore.QSize(20, 0))
        self.frame_size_grip.setMaximumSize(QtCore.QSize(20, 16777215))
        self.frame_size_grip.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_size_grip.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_size_grip.setObjectName("frame_size_grip")
        self.horizontalLayout_5.addWidget(self.frame_size_grip)
        self.verticalLayout_6.addWidget(self.bottomBar)
        self.verticalLayout_2.addWidget(self.contentBottom)
        self.appLayout.addWidget(self.contentBox)
        self.verticalLayout_20.addWidget(self.classApp)
        MainWindow.setCentralWidget(self.styleSheet)

        self.retranslateUi(MainWindow)
        self.myStackedWidget.setCurrentIndex(1)
        self.page1ChooseMajorComboBox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.titleLeftApp.setText(_translate("MainWindow", "辅助编排课程"))
        self.titleLeftDescription.setText(_translate("MainWindow", "适合计算机学生体质的课程表"))
        self.toggleButton.setText(_translate("MainWindow", "隐藏"))
        self.btn_home.setText(_translate("MainWindow", "导入数据"))
        self.btn_graphic.setText(_translate("MainWindow", "拓扑显示"))
        self.btn_human.setText(_translate("MainWindow", "总体效果"))
        self.btn_look.setText(_translate("MainWindow", "具体课表"))
        self.toggleLeftBox.setText(_translate("MainWindow", "其他"))
        self.extraLabel.setText(_translate("MainWindow", "发现隐藏栏咯"))
        self.extraCloseColumnBtn.setToolTip(_translate("MainWindow", "Close left box"))
        self.btn_heart.setText(_translate("MainWindow", "帮助文档"))
        self.btn_out.setText(_translate("MainWindow", "退出软件"))
        self.btn_refer.setText(_translate("MainWindow", "More"))
        self.extraTextEdit.setMarkdown(_translate("MainWindow", "`排课系统  由Python和Pyside制作而成，页面制作参考B站up“有只小新”和“Bemark”的Qt指导教程。     Created by: Han\n"
"Yufan  参考文档汇总  https://devizoe.notion.site/45bdac8f452c4fde86e1fa2584fabfea?pvs=4\n"
"个人声明  项目仅为学习 参考众多网上资源`\n"
"\n"
""))
        self.extraTextEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'SimHei\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:6px; margin-bottom:6px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Courier New\';\">排课系统</span>  <span style=\" font-family:\'Courier New\';\">由Python和Pyside制作而成，页面制作参考B站up“有只小新”和“Bemark”的Qt指导教程。</span>  <span style=\" font-family:\'Courier New\';\"> </span>  <span style=\" font-family:\'Courier New\';\">Created by: Han Yufan</span>  <span style=\" font-family:\'Courier New\';\">参考文档汇总</span>  <span style=\" font-family:\'Courier New\';\">https://devizoe.notion.site/45bdac8f452c4fde86e1fa2584fabfea?pvs=4</span>  <span style=\" font-family:\'Courier New\';\">个人声明</span>  <span style=\" font-family:\'Courier New\';\">项目仅为学习 参考众多网上资源</span></p></body></html>"))
        self.titleRightInfo.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt;\">排课辅助系统</span></p></body></html>"))
        self.colorTopBtn.setToolTip(_translate("MainWindow", "切换主题色"))
        self.minimizeAppBtn.setToolTip(_translate("MainWindow", "最小化"))
        self.maximizeRestoreAppBtn.setToolTip(_translate("MainWindow", "最大化"))
        self.closeAppBtn.setToolTip(_translate("MainWindow", "关闭"))
        self.page1ChooseFileLabel.setText(_translate("MainWindow", "选择包含专业信息的表单文件"))
        self.page1ChooseFileLineEdit.setPlaceholderText(_translate("MainWindow", "请输入文件"))
        self.page1ChooseFileBtn.setText(_translate("MainWindow", " 选择文件"))
        self.page1ChooseMajorLabel.setText(_translate("MainWindow", "选择专业   "))
        self.page1ChooseMajorComboBox.setCurrentText(_translate("MainWindow", "信息安全"))
        self.page1ChooseMajorComboBox.setItemText(0, _translate("MainWindow", "信息安全"))
        self.page1ChooseMajorComboBox.setItemText(1, _translate("MainWindow", "计算机科学与技术"))
        self.page1ChooseMajorComboBox.setItemText(2, _translate("MainWindow", "物联网工程"))
        self.page1ChooseClassLabel.setText(_translate("MainWindow", "查询课程   "))
        self.page1ChooseClassLineEdit.setPlaceholderText(_translate("MainWindow", "请输入要查询的课程名称"))
        item = self.page1TableWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.page1TableWidget.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.page1TableWidget.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        item = self.page1TableWidget.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "4"))
        item = self.page1TableWidget.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "5"))
        item = self.page1TableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "课程名称"))
        item = self.page1TableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "学分"))
        item = self.page1TableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "学时"))
        item = self.page1TableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "先修课程"))
        item = self.page1TableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "简介"))
        item = self.page2TableWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "新建行"))
        item = self.page2TableWidget.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "新建行"))
        item = self.page2TableWidget.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "新建行"))
        item = self.page2TableWidget.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "新建行"))
        item = self.page2TableWidget.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "新建行"))
        item = self.page2TableWidget.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "新建行"))
        item = self.page2TableWidget.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "新建行"))
        item = self.page2TableWidget.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "新建行"))
        item = self.page2TableWidget.verticalHeaderItem(8)
        item.setText(_translate("MainWindow", "新建行"))
        item = self.page2TableWidget.verticalHeaderItem(9)
        item.setText(_translate("MainWindow", "新建行"))
        item = self.page2TableWidget.verticalHeaderItem(10)
        item.setText(_translate("MainWindow", "新建行"))
        item = self.page2TableWidget.verticalHeaderItem(11)
        item.setText(_translate("MainWindow", "新建行"))
        item = self.page2TableWidget.verticalHeaderItem(12)
        item.setText(_translate("MainWindow", "新建行"))
        item = self.page2TableWidget.verticalHeaderItem(13)
        item.setText(_translate("MainWindow", "新建行"))
        item = self.page2TableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "先修课程"))
        item = self.page2TableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "后修课程"))
        self.clearPhotoBtn.setText(_translate("MainWindow", "清空拓扑图"))
        self.reloadPhotoBtn.setText(_translate("MainWindow", "更新拓扑图"))
        self.page3InfoLabel_2.setText(_translate("MainWindow", "交互画布"))
        self.page4AdjustLabel.setText(_translate("MainWindow", "调整课程"))
        self.page4AdjustLinetext.setPlaceholderText(_translate("MainWindow", "请输入要调整的课程名称"))
        self.page4LeftBtn.setToolTip(_translate("MainWindow", "调整到前一学期"))
        self.page4RightBtn.setToolTip(_translate("MainWindow", "调整到后一学期"))
        self.page4XueShiLinetext.setPlaceholderText(_translate("MainWindow", "请输入学期最大学时，上限280"))
        self.page4PngBtn.setText(_translate("MainWindow", "导出为png文件"))
        item = self.page4TableWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "新建行"))
        item = self.page4TableWidget.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "新建行"))
        item = self.page4TableWidget.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "新建行"))
        item = self.page4TableWidget.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "新建行"))
        item = self.page4TableWidget.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "新建行"))
        item = self.page4TableWidget.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "新建行"))
        item = self.page4TableWidget.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "新建行"))
        item = self.page4TableWidget.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "新建行"))
        item = self.page4TableWidget.verticalHeaderItem(8)
        item.setText(_translate("MainWindow", "新建行"))
        item = self.page4TableWidget.verticalHeaderItem(9)
        item.setText(_translate("MainWindow", "新建行"))
        item = self.page4TableWidget.verticalHeaderItem(10)
        item.setText(_translate("MainWindow", "新建行"))
        item = self.page4TableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "大一上"))
        item = self.page4TableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "大一下"))
        item = self.page4TableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "大二上"))
        item = self.page4TableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "大二下"))
        item = self.page4TableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "大三上"))
        item = self.page4TableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "大三下"))
        item = self.page4TableWidget.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "大四上"))
        item = self.page4TableWidget.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "大四下"))
        self.writerLabel.setText(_translate("MainWindow", "By: Han Yufan"))
        self.version.setText(_translate("MainWindow", "v1.0"))
